name: Automatic Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome
        run: echo Start deploying Thieng Proxy
      - name: Build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuphanson/thieng-proxy
          tags: latest
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATEKEY }}
          script: |
            docker stop proxy
            docker rm proxy
            docker pull tuphanson/thieng-proxy
            docker run -d -p 80:80 -p 443:443 -v /etc/letsencrypt:/etc/letsencrypt --name proxy tuphanson/thieng-proxy
            docker network connect --ip 172.18.0.2 thieng-net proxy
